name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Corrected from "pthon-version"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py

      - name: Push Repo
        env:  # Ensures git push works in GitHub Actions
          GIT_AUTHOR_NAME: Merfan-Halah
          GIT_AUTHOR_EMAIL: merfan.halah@gmail.com
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git add .
          git commit -m "Modified Feed" || echo "No changes to commit"
          git push
